language: php

php:
  - '5.6'
  - '7.0'

script:
  - composer install
  - php vendor/bin/codecept run unit --coverage --coverage-xml

after_script:
  - travis_retry php vendor/bin/coveralls

notifications:
  email: false